name: TakhtJang
version: ${project.version}
author: mine215
main: me.mine215.takhtjang.TakhtJang

commands:
  kit:
    description: Gives a kit
    usage: /<command> <kit>
    permission: takhtjang.admin
  hub:
    description: Goes hub
    usage: /<command>
  shop:
    description: Opens the shop
    usage: /<command>
  reset:
    description: Resets the map
    usage: /<command>
    permission: takhtjang.admin
  togglegen:
    description: Toggles resource generation
    usage: /<command>
    permission: takhtjang.admin
  join:
    description: Joins game
    usage: /<command> <team color>
  play:
    description: Joins a game
    usage: /<command>
  p:
    description: Party command
    usage: /<command> <name>
  party:
    description: Party command
    usage: /<command> <name>
  rank:
    description: Rank command
    usage: /<command> <set|remove> <player name> [owner|admin|content|legend]
    permission: takhtjang.owner
  permission:
    description: Gives permissions
    usage: /<command> <give|remove> <player name> <permission name>